### ISSUE TITLE
honyomi addでサムネイル画像を生成させない様にしたい

### ISSUE THREAD

**Issue by tyru** [ongaeshi/honyomi#3]
[この記事](http://ongaeshi.hatenablog.com/entry/ideal-reading-system)でHonyomiの存在を知り、使わせて頂いています。
ありがとうございます。

そこで、Honyomiを使わせて頂いて一つ問題がありまして、
`honyomi add`すると、`~/.honyomi/images/`以下にサムネイル画像？を生成しているようですが、
そのため大量のサムネイル画像が作られてしまい、
たまたまサーバのディスク容量が少なかったためDisk Fullになってしまいました。
（大体`~/.honyomi/db`が2GBに対し`~/.honyomi/images`は14GB作られていました）

私にとってはHonyomiを全文検索エンジンとしてのみ使いたいので、サムネイルは必要ありません。
そこで[ソースコードの該当箇所](https://github.com/ongaeshi/honyomi/blob/0641a471ddb9910bc8ae88cc64a21d792a95c43b/lib/honyomi/database.rb#L45)を以下のようにコメントアウトしてみた所、サムネイル画像は作られないようになりました。

        #add_image(book.id, home_dir) if Util.exist_command?('pdftoppm')

私としてはこれを`honyomi add`のオプション引数等で生成しない様に指定したいのですが、そのようなオプション引数の追加は可能でしょうか。

**Comment by ongaeshi** [comment]
使っていただいてありがとうございます。

`honyomi add --no-image `

のようなオプションを次のバージョンで追加しようと思います。それまでは上記パッチで運用していただければと思います。 

すでに作られてしまったサムネイル画像は `~/.honyomi/image` 以下のbook idに相当するフォルダごと消せば削除できるはずです。

**Comment by tyru** [comment]
ありがとうございます！
とりあえずコメントアウトした状態で運用していこうと思います。
サムネイル画像についても了解です。

**Comment by ongaeshi** [comment]
追加しました。次回リリースに反映されます。

**Comment by tyru** [comment]
対応して頂きありがとうございました！
助かります！

**Comment by ongaeshi** [comment]
honyomi 1.5 から使えるようになります https://github.com/ongaeshi/honyomi/blob/master/HISTORY.md

また画像の追加、削除をWebアプリからもできるようになります。

**Comment by tyru** [comment]
ありがとうございます！
ちなみにいまいちgemの仕組みがよく分かってないのですが、現在 gem install honyomi したら1.5が入るってことで合ってますでしょうか？
それとも1.5というよりmasterが入るのでしょうか？
若干趣旨が違う質問ですみません。

**Comment by ongaeshi** [comment]
> 現在 gem install honyomi したら1.5が入るってことで合ってますでしょうか？
> はい！その通りです。今インストールすると1.5がインストールされるはずです。

**Comment by tyru** [comment]
了解です！ありがとうございます！
