### ISSUE TITLE
No such file or directory - pdftotext

### ISSUE THREAD

**Issue by arnoldtonderaimarunda** [ongaeshi/honyomi#4]
When I add PDFs using honyomi we I get the error

`No such file or directory - pdftotext`

**Comment by ongaeshi** [comment]
You need pdftotext bundled with poppler.

Please refer to [docker-honyomi/Dockerfile](https://github.com/ongaeshi/docker-honyomi/blob/master/Dockerfile).

**Comment by arnoldtonderaimarunda** [comment]
Thank you, understood
